### ISSUE TITLE
未能跑通项目中的案例

### ISSUE THREAD

**Issue by SeeFlowerX** [Abbbbbi/UniDa#1]
应该是项目没有完成（借此打听进度）。

不过非常感谢大佬的努力，希望能早日完成~

---

hook_code注释掉了（输出实在是太多了），最后报错如下，完整日志见附件。

粗略看项目代码应该处理都比较完善了，但是不知道为何init没能做完，还请大佬赐教。

```
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x1
[23:20:16 3562] INFO [Emulator.linker.Module] (Module.py:23) - Calling Init_Array libwechatnormsg.so 0x40043C35 function: 0x3C35 
[23:20:16 3562] INFO [Emulator.linker.Module] (Module.py:23) - Calling Init_Array libwechatnormsg.so 0x40043CB5 function: 0x3CB5 
[23:20:16 3562] INFO [Emulator.linker.Module] (Module.py:23) - Calling Init_Array libwechatnormsg.so 0x40043EAD function: 0x3EAD 
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x3
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x1
[23:20:16 3562] INFO [Emulator.linker.Module] (Module.py:23) - Calling Init_Array libwechatnormsg.so 0x400440AD function: 0x40AD 
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x3
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x1
[23:20:16 3562] INFO [Emulator.linker.Module] (Module.py:23) - Calling Init_Array libwechatnormsg.so 0x400440CD function: 0x40CD 
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x3
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x1
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x3
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x1
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x3
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x1
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x3
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x1
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x3
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x1
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x3
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x1
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x3
[23:20:16 3562] DEBUG [Emulator.vm.ARM32SyscallHandler] (ARM32SyscallHandler.py:755) - mprotect address= 0x40698000, alignedAddress= 0x40698000, offset= 0, length= 4096, alignedLength= 4096, prot= 0x1
[23:20:16 3562] INFO [Emulator.linker.Module] (Module.py:23) - Calling Init_Array libwechatnormsg.so 0x40044191 function: 0x4191 
Traceback (most recent call last):
  File "/home/kali/Desktop/test/UniDa/Emulator/Emulator.py", line 75, in call_native
    self.mu.emu_start(addr, LR)
  File "/home/kali/miniconda3/envs/UniDa/lib/python3.8/site-packages/unicorn/unicorn.py", line 341, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "UniDa.py", line 18, in <module>
    emulator.loadLibrary("libwechatnormsg.so", True)
  File "/home/kali/Desktop/test/UniDa/Emulator/Emulator.py", line 62, in loadLibrary
    return self.linker.do_dlopen(fileName, callInit)
  File "/home/kali/Desktop/test/UniDa/Emulator/linker/Linker.py", line 113, in do_dlopen
    module.callInit(self.emulator)
  File "/home/kali/Desktop/test/UniDa/Emulator/linker/Module.py", line 24, in callInit
    emulator.call_native(fun_addr)
  File "/home/kali/Desktop/test/UniDa/Emulator/Emulator.py", line 77, in call_native
    raise Exception(UcError)
Exception: <class 'unicorn.unicorn.UcError'>
```
[uni.log](https://github.com/Abbbbbi/UniDa/files/7686300/uni.log)

**Comment by Abbbbbi** [comment]
确实还没完成，最近一个月刚找到工作，后面会慢慢修复+完善

**Comment by SeeFlowerX** [comment]
感谢回复，静候完善
